<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Migrations\AbortMigrationException;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20201220134817 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE albe_cqrslite_command_domain_model_command (commandid VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, issuedby VARCHAR(255) DEFAULT NULL, issuedfrom VARCHAR(255) NOT NULL, issuedon DATETIME NOT NULL, meta LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', payload LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', INDEX type_idx (type, issuedOn), PRIMARY KEY(commandid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE albe_cqrslite_command_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, username VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_43426279F85E0677 (username), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE albe_cqrslite_query_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, type VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE albe_cqrslite_query_domain_model_userreport (persistence_object_identifier VARCHAR(40) NOT NULL, type VARCHAR(255) NOT NULL, count INT NOT NULL, INDEX type_idx (type), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('DROP TABLE albe_cqrslite_command_domain_model_command');
        $this->addSql('DROP TABLE albe_cqrslite_command_domain_model_user');
        $this->addSql('DROP TABLE albe_cqrslite_query_domain_model_user');
        $this->addSql('DROP TABLE albe_cqrslite_query_domain_model_userreport');
    }
}